###
GET http://localhost:8082/search

POST http://localhost:8082/gpt
Content-Type: application/json

{
    "content": "Hello, how are you?"
}

###
POST http://localhost:8082/gpt/search
Content-Type: application/json

{
    "content": "Do you know What is the current date?"
}

